### ISSUE TITLE
How to configure oozie

### ISSUE THREAD

**Issue by christopinka** [mapr-demos/mapr-db-60-getting-started#21]
Is oozie included in the image? Can you help with a version that includes oozie install and config? Thank you.

**Comment by christopinka** [comment]
Would it be good enough to follow here for unsecure?

https://docs.datafabric.hpe.com/70/AdvancedInstallation/InstallOozie.html?hl=install%2Coozie

**Comment by tdunning** [comment]
Included in what image?

In general we are strongly deprecating oozie. Use is declining rapidly and
it is still just as difficult as ever. Much better options are available.

**Comment by christopinka** [comment]
This image - https://github.com/mapr-demos/mapr-db-60-getting-started/blob/master/mapr_devsandbox_container_setup.sh

Unfortunately, it seems we're stuck with it for the time being.

What are the other options? Airflow... others? mapr supported option?

**Comment by tdunning** [comment]
Airflow is supported by HPE Ezmeral, yes.

There are a number of other options, but Airflow is pretty simple. Adding Liminal to simplify building images is also nice.

**Comment by christopinka** [comment]
Is the dockerfile available for dev-sandbox-container? https://hub.docker.com/r/maprtech/dev-sandbox-container
